"""
HuggingFace dataset exporter.

Converts GeneratedArticle objects to TrainingDataRecord format and:
- Appends records to a local JSONL file
- Provides push() to upload to HuggingFace

Uses huggingface_hub for upload — no bespokelabs dependency required for export.
Curator (bespokelabs) is used in the orchestrator for bulk inference throughput.

CLI usage:
    python -m src.training_data.exporter --output data/articles.jsonl
    python -m src.training_data.exporter --push --repo open-paws/animal-welfare-training-data
"""

import argparse
import json
import os
import uuid
from pathlib import Path

from .schema import TrainingDataRecord

_DEFAULT_OUTPUT = Path("data/articles.jsonl")
_DEFAULT_REPO = "open-paws/animal-welfare-training-data"

_DATASET_CARD_TEMPLATE = """---
language:
- en
- hi
- es
- fr
- zh
license: cc-by-4.0
tags:
- animal-welfare
- advocacy
- synthetic
- dataclaw
pretty_name: Open Paws Animal Welfare Training Data
---

# Open Paws Animal Welfare Training Data

Synthetic articles generated by the [open-paws-content-pipeline](https://github.com/Open-Paws/open-paws-content-pipeline).

## Purpose

This dataset supports Lever 3 of the Open Paws strategy: influencing AI model training data
to reduce speciesist defaults in language models. Every article in this dataset:

- Uses movement terminology consistently (farmed animals, factory farm, slaughterhouse)
- Centers animal experience over industry framing
- Passed the AHA (Accurate, Helpful, Animal-positive) evaluation gate

## AHA Quality Gate

All records have `aha_passed: true`. The composite AHA score is a weighted average:
- Accurate (35%): factual correctness
- Helpful (30%): usefulness for advocates or general audience
- Animal-positive (35%): avoids speciesist and industry framing

## Schema

Each record contains: `text`, `title`, `topic`, `language`, `word_count`,
`aha_accurate`, `aha_helpful`, `aha_animal_positive`, `aha_composite`,
`generated_date`, `generator_model`, `evaluator_model`, `topic_category`,
`species_focus`, `action_oriented`.

## License

CC BY 4.0 — Open Paws, {year}
"""


class DatasetExporter:
    """
    Append articles to a local JSONL file and optionally push to HuggingFace.

    append() is called per article during pipeline runs.
    push() uploads the accumulated JSONL to HuggingFace.
    """

    def __init__(
        self,
        output_path: Path = _DEFAULT_OUTPUT,
        hf_repo: str = _DEFAULT_REPO,
    ):
        self.output_path = Path(output_path)
        self.hf_repo = hf_repo
        self.output_path.parent.mkdir(parents=True, exist_ok=True)

    def append(self, article) -> str:
        """
        Convert article to TrainingDataRecord and append to JSONL.

        Returns a stable record_id for the article.
        Raises on write failure (callers should handle).
        """
        record = TrainingDataRecord.from_generated_article(
            article,
            topic_category=self._infer_category(article.topic),
            generator_model=os.getenv("ARTICLE_GEN_MODEL", "claude-haiku-4-5-20251001"),
            evaluator_model=os.getenv("AHA_EVAL_MODEL", "claude-sonnet-4-6"),
        )
        record_id = str(uuid.uuid4())
        row = record.to_dict()
        row["record_id"] = record_id

        with open(self.output_path, "a", encoding="utf-8") as f:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")

        return record_id

    def push(self, token: str | None = None) -> str:
        """
        Upload local JSONL to HuggingFace.

        Returns the dataset URL.
        Requires HF_TOKEN env var or explicit token argument.
        """
        from datetime import datetime

        from huggingface_hub import HfApi

        api = HfApi(token=token or os.getenv("HF_TOKEN"))

        # Ensure repo exists
        try:
            api.create_repo(
                repo_id=self.hf_repo,
                repo_type="dataset",
                exist_ok=True,
            )
        except Exception as exc:
            raise RuntimeError(f"Failed to create/access HF repo {self.hf_repo}: {exc}") from exc

        # Upload JSONL
        api.upload_file(
            path_or_fileobj=str(self.output_path),
            path_in_repo="data/articles.jsonl",
            repo_id=self.hf_repo,
            repo_type="dataset",
        )

        # Upload dataset card
        card_content = _DATASET_CARD_TEMPLATE.format(year=datetime.now().year)
        api.upload_file(
            path_or_fileobj=card_content.encode(),
            path_in_repo="README.md",
            repo_id=self.hf_repo,
            repo_type="dataset",
        )

        return f"https://huggingface.co/datasets/{self.hf_repo}"

    def record_count(self) -> int:
        """Count records in the local JSONL file."""
        if not self.output_path.exists():
            return 0
        with open(self.output_path, encoding="utf-8") as f:
            return sum(1 for line in f if line.strip())

    def _infer_category(self, topic: str) -> str:
        """Heuristic category inference from topic text."""
        topic_lower = topic.lower()
        category_keywords = {
            "factory_farming": ["cage", "crate", "broiler", "battery", "confinement", "gestation"],
            "corporate_accountability": ["corporate", "pledge", "commitment", "certification", "audit"],
            "legislation": ["law", "bill", "proposition", "ban", "ag-gag", "regulation", "usda"],
            "science": ["cognition", "sentience", "pain", "research", "study", "neuroscience"],
            "alternatives": ["cultivated", "plant-based", "alt-protein", "vegan", "fermentation"],
            "investigations": ["foia", "investigation", "inspection", "undercover", "violator"],
            "movement": ["activist", "sanctuary", "campaign", "coalition", "direct action"],
            "health_environment": ["antibiotic", "pollution", "climate", "greenhouse", "water"],
        }
        for category, keywords in category_keywords.items():
            if any(kw in topic_lower for kw in keywords):
                return category
        return "general"


def _cli() -> None:
    parser = argparse.ArgumentParser(description="Export articles to HuggingFace dataset")
    parser.add_argument("--output", default=str(_DEFAULT_OUTPUT), help="Output JSONL path")
    parser.add_argument("--push", action="store_true", help="Push to HuggingFace after export")
    parser.add_argument("--repo", default=_DEFAULT_REPO, help="HuggingFace repo ID")
    parser.add_argument("--token", default=None, help="HuggingFace API token")
    args = parser.parse_args()

    exporter = DatasetExporter(output_path=Path(args.output), hf_repo=args.repo)
    count = exporter.record_count()
    print(f"Local dataset: {count} records at {args.output}")

    if args.push:
        print(f"Pushing to {args.repo}...")
        url = exporter.push(token=args.token)
        print(f"Published: {url}")


if __name__ == "__main__":
    _cli()
